/** @file superloop.c
 *
 * @brief This module contains the firmware superloop, code in here should be
 * added to the main function generated by the CubeMX tools. By convention we
 * want this to be the only module accessed from the CubeMX generated main
 * function.
 *
 * @par
 * COPYRIGHT NOTICE: (c) 2024 DalMAST. All rights reserved.
 */

#include "superloop.h"

// CubeMx-generated header files:
#include "stm32u0xx_hal.h"
// User-generated header files:
#include "blink.h"
#include "uart.h"

/*!
 * @brief This function should be called before the superloop.
 */
void
superloop_init (void)
{
    uart_init();
    blink_init();
}

/*!
 * @brief This function should be called within the superloop.
 */
void
superloop_run (void)
{
    blink_superloop();
    uart_superloop();
}